apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-application
  namespace: argocd
spec:
  project: default
  destination: 
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/duongtanton/DACNPM-cicd
    targetRevision: HEAD
    path: helm-charts
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
# 48pgmcFkGsXRBX3n
