replicaCount: 1
image:
  repository: tonduong/mimo-clone-ui
  tag: 16
  pullPolicy: Always
service:
  type: NodePort
  port: 3000
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: duongtanton.click
      paths:
        - path: /
          pathType: Prefix
          
