autoscaling: 
  enabled: false
replicaCount: 1
selectorLabels: mimo-clone-ui
podAnnotations: {}
podLabels: {}
imagePullSecrets: []
serviceAccountName: default
podSecurityContext: {}
image:
  repository: tonduong/mimo-clone-ui
  tag: latest
  pullPolicy: Always
securityContext: {}
service:
  port: 3000
livenessProbe: {}
readinessProbe: {}
resources: {}
volumeMounts: []
nodeSelector: {}
affinity: {}
tolerations: []
# 
service:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
      name: http