replicaCount: 1
image:
  repository: tonduong/api-gateway
  tag: 6
  pullPolicy: Always
service:
  type: NodePort
  port: 3000
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: duongtanton.click
      paths:
        - path: /
          pathType: Prefix
