name: CI/CD for Next.js

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      TOKEN:
        required: true
      EC2_HOST:
        required: true
      EC2_USERNAME:
        required: true
      EC2_PRIVATE_KEY:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: demo-microservices
          file: demo-microservices/Dockerfile
          tags: tonduong/demo-microservices:${{ github.run_number }}
          push: true

      - name: Checkout CICD repository
        uses: actions/checkout@v4
        with:
          repository: duongtanton/DACNPM-cicd
          path: temp
          token: ${{ secrets.TOKEN }}       

      - name: Update image.tag demo-microservices/values.yaml
        run: |
          cd temp
          sed -i "s/tag: .*/tag: ${{ github.run_number }}/g" helm/charts/demo-microservices/values.yaml
          git add helm/charts/demo-microservices/values.yaml
          git config --global user.name 'duongtanton'
          git config --global user.email '20120598@student.hcmus.edu.vn'
          git commit -m "Update image.tag demo-microservices/values.yaml to ${{ github.run_number }}"
          git push origin main
      
      - name: Update image.tag demo-microservices/values.yaml
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /opt/demo-microservices
            sudo sed -i "s/image: tonduong/demo-microservices: .*/image: tonduong/demo-microservices: ${{ github.run_number }}/g" /opt/demo-microservices/docker-compose.yml
            sudo docker-compose down --rmi 'all'
            sudo docker-compose up -d