name: CI/CD for Next.js

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: tonduong/demo-microservices:${{ github.run_number }}

      - name: Checkout CICD repository
        uses: actions/checkout@v4
        with:
          repository: duongtanton/DACNPM-cicd
          token: ${{ secrets.GITHUB_TOKEN }}       

      - name: Commit update image.tag demo-microservices/values.yaml
        run: |
          sed -i "s/tag: .*/tag: ${{ github.run_number }}/g" dacnpm-charts/charts/demo-microservices/values.yaml
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dacnpm-charts/charts/demo-microservices/values.yaml
          git commit -m "Update image.tag demo-microservices/values.yaml to ${{ github.run_number }}"
      - name: Push update image.tag demo-microservices/values.yaml
        uses: ad-m/github-push-action@master
        with:
          repository: duongtanton/DACNPM-cicd
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main