name: CI/CD for Next.js

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: tonduong/demo-microservices
          tags: ${{ github.run_number }}
          registry: docker.io
          dockerfile: demo-microservices/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Update demo-microservices/values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          repository: duongtanton/DACNPM-cicd
          branch: main
          valueFile: 'dacnpm-charts/charts/demo-microservices/values.yaml'
          propertyPath: 'image.tag'
          value: ${{ github.run_number }}
          message: 'Update demo-microservices/values.yaml to ${{ github.run_number }}'